wmariuss/awesome-devops

README.md
Thank you for the maintenance!
=> Add gitploy to CI/CD

README.md
Fix some spelling and grammar errors. Reword some tool and section descriptions for clarity.
=> Fix some spelling and grammar errors

README.md
Hi, [Stacktape](https://stacktape.com/) CEO here.
After 2.5 years in development, I'm happy to introduce Stacktape - Developer-friendly Infrastructure as a Code framework built on top of AWS.
- Stacktape allows to develop, deploy and run applications on AWS with 98% less configuration.
- It automates infrastructure management, source-code packaging, deployments, local debugging & more.
- Supports 20+ "higher-level" AWS infrastructure components, including Lambda functions, Containers, SQL databases, Redis clusters, Load balancers, and more. It also supports other fully-managed infrastructure services deployable to AWS (currently MongoDB Atlas clusters and Upstash Redis/Kafka).
- A typical production-grade REST API is ~30 lines of Stacktape config (compared to ~600-800 lines of …
=> Add Stacktape

README.md
=> Add KubeMQ

README.md
=> Add Score to Automation & Orchestration

.github/workflows/deploy.yml, README.md, docs/contribution.md, docs/index.md, mkdocs.yml, requirements.txt
* Better sections with more links
* Upgrade version for the `mkdocs`
* Update the config for `mkdocs`
* Small changes (site and CI workflows)
=> Upgrade webiste

README.md
Added ScyllaDB (https://www.scylladb.com/) to NoSQL Databases section.
=> added ScyllaDB

README.md
Free and open source project powered by the jsDelivr community https://github.com/jsdelivr#the-globalping-platform
=> Add Globalping CLI

README.md
Add an open-source policy-as-code software that provides analytics for multi-cloud and SaaS.
=> Add an open-source policy-as-code software that provides analytics for multi-cloud and SaaS.

README.md
I'm sorry I misplaced the project category. Let me correct it now.
=> Modify the selefra category

README.md
DevHub is a european source code hosting provider with strong focus on privacy, security and performance.
=> Add DevHub

README.md
=> Remove DevHub

README.md
https://github.com/wmariuss/awesome-devops/issues/126
=> Update README.md #126

README.md
Added Meshery to the awesome DevOps list
=> add meshery to list

README.md
👋 Hi! I'd like to be able to add [Canine](https://canine.sh) to the Application Platforms section. Makes it super easy to deploy a containerized application to Kubernetes or K3s, with full gitops & CD integration
Its maintained and has updates weekly!
=> added Canine to application platforms

README.md
Added Middleware in Monitoring section.
Middleware APM repo - https://github.com/middleware-labs/mw-agent/
=> Add Middleware to Monitoring Section

README.md
This PR adds [CloudRay](https://cloudray.io), a centralized platform for managing servers, organizing Bash scripts, and automating infrastructure tasks across cloud and virtual machines.
=> added CloudRay

README.md
I've added a new book to the list of recommended books: _[Fundamentals of DevOps and Software Delivery](https://www.fundamentals-of-devops.com/)_.
=> Add Fundamentals of DevOps and Software Delivery

README.md
Add Semaphore Community Edition to the list of on-premise CI/CD
=> Add Semaphore CE

README.md
Application: OneCompiler
Category: Sharing
Link: https://github.com/onecompiler
OneCompiler is an online compiler and development environment that supports 70+ programming languages and databases. It allows users to write, run and share code online.
The tool fits well in the Sharing section as it enables developers to:
- Write and test code in browser
- Share code snippets with others
- Collaborate on code examples
=> Add OneCompiler to Sharing section
